---
title: "Submitting Data to the Herbarium EXAMPLE"
author: "Jasmine"
date: '2019-04-29'
output: html_document
---

specify some variables
```{r}
#bceause Country and Province state were not specified before in the Master list
ctry <- "Canada"
prov <- "British Columbia"

pid <- "PTM_CArbuscula"
```


Make sure you have these packages installed
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
library(googlesheets)
library(here)
library(taxize)
library(ptm)
library(worrms)
```

load your data
```{r}
file <- "Master Collector Excel Templates_Kyra2019.xlsx"
s_num <- 2
row_skip <- 4
```

## Load in your spreadsheet with your PTM numbers
```{r}
original <- read_xlsx(here("./data/",file), sheet = s_num, skip = row_skip)

#removes rows that are not specimens (ie NA)
df_na <- filter(original, str_detect(original$`Collector Number`, "PTM"))
```

## Load in herbarium template
```{r}
collector_a <- read_xlsx("Master-Collector-Excel-Templates-20190429.xlsx",sheet = 2, skip = 4)
```


## Read in the master list
```{r}
new <- masterlist()
```

## Select the rows
```{r}
df <- new %>% 
  mutate(num = paste0("PTM",`PTM#`)) %>% 
  filter(num %in% df_na$`Collector Number`)
```

### Figure out which name to use
```{r}
df_nm <- df %>% 
  mutate(choice = if_else(is.na(df$`Final determination`),
                      df$`Determination in the field`,
                      df$`Final determination`),
         gs = choice) %>% 
  separate(choice, c("Genus","Species"), " ")

# check
names <- cbind(df$`Final determination`, df$`Determination in the field`, df$`genetic match/notes`)
```

### Phylum Class Family
- gets authorships using the worms database
```{r}
higher <- wm_records_names(df_nm$gs) %>% 
  map_dfr(.,`[`)
```

```{r}
meta <- df_nm %>%
  mutate(Herbarium = "UBC",
         LabelQty = 1,
         Qualifier = "") %>% 
  left_join(higher, by = c("gs" = "scientificname"))

## select columns
herb <- meta %>% 
  select(`PTM#`, Herbarium, LabelQty, phylum, class, Genus,Qualifier, Species, authority,
         Locality,Latitude, Longitude, Habitat, Depth, `Reproductive Status`, `Date Collected`, `Primary Collector`, `PTM#`,`Determined by`, `Determination Date`, `Field Notes` )
```

```{r}
write_csv(herb,"output/2019Sept24_KyraCoralline.csv", na = "")
```

